/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VipTransfersRouteImport } from './routes/vip-transfers'
import { Route as ToursRouteImport } from './routes/tours'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as FleetRouteImport } from './routes/fleet'
import { Route as DriveWithUsRouteImport } from './routes/drive-with-us'
import { Route as CorporateTravelRouteImport } from './routes/corporate-travel'
import { Route as CorporateBookingRouteImport } from './routes/corporate-booking'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BookRouteImport } from './routes/book'
import { Route as AirportTransfersRouteImport } from './routes/airport-transfers'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const VipTransfersRoute = VipTransfersRouteImport.update({
  id: '/vip-transfers',
  path: '/vip-transfers',
  getParentRoute: () => rootRouteImport,
} as any)
const ToursRoute = ToursRouteImport.update({
  id: '/tours',
  path: '/tours',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const FleetRoute = FleetRouteImport.update({
  id: '/fleet',
  path: '/fleet',
  getParentRoute: () => rootRouteImport,
} as any)
const DriveWithUsRoute = DriveWithUsRouteImport.update({
  id: '/drive-with-us',
  path: '/drive-with-us',
  getParentRoute: () => rootRouteImport,
} as any)
const CorporateTravelRoute = CorporateTravelRouteImport.update({
  id: '/corporate-travel',
  path: '/corporate-travel',
  getParentRoute: () => rootRouteImport,
} as any)
const CorporateBookingRoute = CorporateBookingRouteImport.update({
  id: '/corporate-booking',
  path: '/corporate-booking',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const AirportTransfersRoute = AirportTransfersRouteImport.update({
  id: '/airport-transfers',
  path: '/airport-transfers',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/airport-transfers': typeof AirportTransfersRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/corporate-booking': typeof CorporateBookingRoute
  '/corporate-travel': typeof CorporateTravelRoute
  '/drive-with-us': typeof DriveWithUsRoute
  '/fleet': typeof FleetRoute
  '/services': typeof ServicesRoute
  '/tours': typeof ToursRoute
  '/vip-transfers': typeof VipTransfersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/airport-transfers': typeof AirportTransfersRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/corporate-booking': typeof CorporateBookingRoute
  '/corporate-travel': typeof CorporateTravelRoute
  '/drive-with-us': typeof DriveWithUsRoute
  '/fleet': typeof FleetRoute
  '/services': typeof ServicesRoute
  '/tours': typeof ToursRoute
  '/vip-transfers': typeof VipTransfersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/airport-transfers': typeof AirportTransfersRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/corporate-booking': typeof CorporateBookingRoute
  '/corporate-travel': typeof CorporateTravelRoute
  '/drive-with-us': typeof DriveWithUsRoute
  '/fleet': typeof FleetRoute
  '/services': typeof ServicesRoute
  '/tours': typeof ToursRoute
  '/vip-transfers': typeof VipTransfersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/airport-transfers'
    | '/book'
    | '/contact'
    | '/corporate-booking'
    | '/corporate-travel'
    | '/drive-with-us'
    | '/fleet'
    | '/services'
    | '/tours'
    | '/vip-transfers'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/airport-transfers'
    | '/book'
    | '/contact'
    | '/corporate-booking'
    | '/corporate-travel'
    | '/drive-with-us'
    | '/fleet'
    | '/services'
    | '/tours'
    | '/vip-transfers'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/airport-transfers'
    | '/book'
    | '/contact'
    | '/corporate-booking'
    | '/corporate-travel'
    | '/drive-with-us'
    | '/fleet'
    | '/services'
    | '/tours'
    | '/vip-transfers'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AirportTransfersRoute: typeof AirportTransfersRoute
  BookRoute: typeof BookRoute
  ContactRoute: typeof ContactRoute
  CorporateBookingRoute: typeof CorporateBookingRoute
  CorporateTravelRoute: typeof CorporateTravelRoute
  DriveWithUsRoute: typeof DriveWithUsRoute
  FleetRoute: typeof FleetRoute
  ServicesRoute: typeof ServicesRoute
  ToursRoute: typeof ToursRoute
  VipTransfersRoute: typeof VipTransfersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vip-transfers': {
      id: '/vip-transfers'
      path: '/vip-transfers'
      fullPath: '/vip-transfers'
      preLoaderRoute: typeof VipTransfersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tours': {
      id: '/tours'
      path: '/tours'
      fullPath: '/tours'
      preLoaderRoute: typeof ToursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fleet': {
      id: '/fleet'
      path: '/fleet'
      fullPath: '/fleet'
      preLoaderRoute: typeof FleetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drive-with-us': {
      id: '/drive-with-us'
      path: '/drive-with-us'
      fullPath: '/drive-with-us'
      preLoaderRoute: typeof DriveWithUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corporate-travel': {
      id: '/corporate-travel'
      path: '/corporate-travel'
      fullPath: '/corporate-travel'
      preLoaderRoute: typeof CorporateTravelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corporate-booking': {
      id: '/corporate-booking'
      path: '/corporate-booking'
      fullPath: '/corporate-booking'
      preLoaderRoute: typeof CorporateBookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/airport-transfers': {
      id: '/airport-transfers'
      path: '/airport-transfers'
      fullPath: '/airport-transfers'
      preLoaderRoute: typeof AirportTransfersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AirportTransfersRoute: AirportTransfersRoute,
  BookRoute: BookRoute,
  ContactRoute: ContactRoute,
  CorporateBookingRoute: CorporateBookingRoute,
  CorporateTravelRoute: CorporateTravelRoute,
  DriveWithUsRoute: DriveWithUsRoute,
  FleetRoute: FleetRoute,
  ServicesRoute: ServicesRoute,
  ToursRoute: ToursRoute,
  VipTransfersRoute: VipTransfersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
