/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VipTransfersRouteImport } from './routes/vip-transfers'
import { Route as ToursRouteImport } from './routes/tours'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as FleetRouteImport } from './routes/fleet'
import { Route as DriveWithUsRouteImport } from './routes/drive-with-us'
import { Route as DistanceRouteImport } from './routes/distance'
import { Route as CorporateTravelRouteImport } from './routes/corporate-travel'
import { Route as CorporateBookingRouteImport } from './routes/corporate-booking'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BookRouteImport } from './routes/book'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AirportTransfersRouteImport } from './routes/airport-transfers'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BookingTokenRouteImport } from './routes/booking.$token'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedAdminTourSettingsRouteImport } from './routes/_authenticated/admin/tour-settings'
import { Route as AuthenticatedAdminSurchargesRouteImport } from './routes/_authenticated/admin/surcharges'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin/settings'
import { Route as AuthenticatedAdminScenicRoutesRouteImport } from './routes/_authenticated/admin/scenic-routes'
import { Route as AuthenticatedAdminReportsRouteImport } from './routes/_authenticated/admin/reports'
import { Route as AuthenticatedAdminPricingPreviewRouteImport } from './routes/_authenticated/admin/pricing-preview'
import { Route as AuthenticatedAdminPricingRouteImport } from './routes/_authenticated/admin/pricing'
import { Route as AuthenticatedAdminPoisRouteImport } from './routes/_authenticated/admin/pois'
import { Route as AuthenticatedAdminPaymentsRouteImport } from './routes/_authenticated/admin/payments'
import { Route as AuthenticatedAdminNotificationsRouteImport } from './routes/_authenticated/admin/notifications'
import { Route as AuthenticatedAdminMileagePricingRouteImport } from './routes/_authenticated/admin/mileage-pricing'
import { Route as AuthenticatedAdminMessagesRouteImport } from './routes/_authenticated/admin/messages'
import { Route as AuthenticatedAdminLogsRouteImport } from './routes/_authenticated/admin/logs'
import { Route as AuthenticatedAdminHourlyRateRouteImport } from './routes/_authenticated/admin/hourly-rate'
import { Route as AuthenticatedAdminFleetRouteImport } from './routes/_authenticated/admin/fleet'
import { Route as AuthenticatedAdminDriversRouteImport } from './routes/_authenticated/admin/drivers'
import { Route as AuthenticatedAdminCustomersRouteImport } from './routes/_authenticated/admin/customers'
import { Route as AuthenticatedAdminCouponsRouteImport } from './routes/_authenticated/admin/coupons'
import { Route as AuthenticatedAdminContentRouteImport } from './routes/_authenticated/admin/content'
import { Route as AuthenticatedAdminBookingsRouteImport } from './routes/_authenticated/admin/bookings'
import { Route as AuthenticatedAdminBannedAddressesRouteImport } from './routes/_authenticated/admin/banned-addresses'
import { Route as AuthenticatedAdminAddressesRouteImport } from './routes/_authenticated/admin/addresses'

const VipTransfersRoute = VipTransfersRouteImport.update({
  id: '/vip-transfers',
  path: '/vip-transfers',
  getParentRoute: () => rootRouteImport,
} as any)
const ToursRoute = ToursRouteImport.update({
  id: '/tours',
  path: '/tours',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const FleetRoute = FleetRouteImport.update({
  id: '/fleet',
  path: '/fleet',
  getParentRoute: () => rootRouteImport,
} as any)
const DriveWithUsRoute = DriveWithUsRouteImport.update({
  id: '/drive-with-us',
  path: '/drive-with-us',
  getParentRoute: () => rootRouteImport,
} as any)
const DistanceRoute = DistanceRouteImport.update({
  id: '/distance',
  path: '/distance',
  getParentRoute: () => rootRouteImport,
} as any)
const CorporateTravelRoute = CorporateTravelRouteImport.update({
  id: '/corporate-travel',
  path: '/corporate-travel',
  getParentRoute: () => rootRouteImport,
} as any)
const CorporateBookingRoute = CorporateBookingRouteImport.update({
  id: '/corporate-booking',
  path: '/corporate-booking',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AirportTransfersRoute = AirportTransfersRouteImport.update({
  id: '/airport-transfers',
  path: '/airport-transfers',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingTokenRoute = BookingTokenRouteImport.update({
  id: '/booking/$token',
  path: '/booking/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminTourSettingsRoute =
  AuthenticatedAdminTourSettingsRouteImport.update({
    id: '/tour-settings',
    path: '/tour-settings',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminSurchargesRoute =
  AuthenticatedAdminSurchargesRouteImport.update({
    id: '/surcharges',
    path: '/surcharges',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminScenicRoutesRoute =
  AuthenticatedAdminScenicRoutesRouteImport.update({
    id: '/scenic-routes',
    path: '/scenic-routes',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminReportsRoute =
  AuthenticatedAdminReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPricingPreviewRoute =
  AuthenticatedAdminPricingPreviewRouteImport.update({
    id: '/pricing-preview',
    path: '/pricing-preview',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPricingRoute =
  AuthenticatedAdminPricingRouteImport.update({
    id: '/pricing',
    path: '/pricing',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPoisRoute = AuthenticatedAdminPoisRouteImport.update({
  id: '/pois',
  path: '/pois',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminPaymentsRoute =
  AuthenticatedAdminPaymentsRouteImport.update({
    id: '/payments',
    path: '/payments',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminNotificationsRoute =
  AuthenticatedAdminNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminMileagePricingRoute =
  AuthenticatedAdminMileagePricingRouteImport.update({
    id: '/mileage-pricing',
    path: '/mileage-pricing',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminMessagesRoute =
  AuthenticatedAdminMessagesRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminLogsRoute = AuthenticatedAdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminHourlyRateRoute =
  AuthenticatedAdminHourlyRateRouteImport.update({
    id: '/hourly-rate',
    path: '/hourly-rate',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminFleetRoute = AuthenticatedAdminFleetRouteImport.update({
  id: '/fleet',
  path: '/fleet',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminDriversRoute =
  AuthenticatedAdminDriversRouteImport.update({
    id: '/drivers',
    path: '/drivers',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCustomersRoute =
  AuthenticatedAdminCustomersRouteImport.update({
    id: '/customers',
    path: '/customers',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCouponsRoute =
  AuthenticatedAdminCouponsRouteImport.update({
    id: '/coupons',
    path: '/coupons',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminContentRoute =
  AuthenticatedAdminContentRouteImport.update({
    id: '/content',
    path: '/content',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminBookingsRoute =
  AuthenticatedAdminBookingsRouteImport.update({
    id: '/bookings',
    path: '/bookings',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminBannedAddressesRoute =
  AuthenticatedAdminBannedAddressesRouteImport.update({
    id: '/banned-addresses',
    path: '/banned-addresses',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAddressesRoute =
  AuthenticatedAdminAddressesRouteImport.update({
    id: '/addresses',
    path: '/addresses',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/airport-transfers': typeof AirportTransfersRoute
  '/auth': typeof AuthRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/corporate-booking': typeof CorporateBookingRoute
  '/corporate-travel': typeof CorporateTravelRoute
  '/distance': typeof DistanceRoute
  '/drive-with-us': typeof DriveWithUsRoute
  '/fleet': typeof FleetRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tours': typeof ToursRoute
  '/vip-transfers': typeof VipTransfersRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/booking/$token': typeof BookingTokenRoute
  '/admin/addresses': typeof AuthenticatedAdminAddressesRoute
  '/admin/banned-addresses': typeof AuthenticatedAdminBannedAddressesRoute
  '/admin/bookings': typeof AuthenticatedAdminBookingsRoute
  '/admin/content': typeof AuthenticatedAdminContentRoute
  '/admin/coupons': typeof AuthenticatedAdminCouponsRoute
  '/admin/customers': typeof AuthenticatedAdminCustomersRoute
  '/admin/drivers': typeof AuthenticatedAdminDriversRoute
  '/admin/fleet': typeof AuthenticatedAdminFleetRoute
  '/admin/hourly-rate': typeof AuthenticatedAdminHourlyRateRoute
  '/admin/logs': typeof AuthenticatedAdminLogsRoute
  '/admin/messages': typeof AuthenticatedAdminMessagesRoute
  '/admin/mileage-pricing': typeof AuthenticatedAdminMileagePricingRoute
  '/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/pois': typeof AuthenticatedAdminPoisRoute
  '/admin/pricing': typeof AuthenticatedAdminPricingRoute
  '/admin/pricing-preview': typeof AuthenticatedAdminPricingPreviewRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/scenic-routes': typeof AuthenticatedAdminScenicRoutesRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/surcharges': typeof AuthenticatedAdminSurchargesRoute
  '/admin/tour-settings': typeof AuthenticatedAdminTourSettingsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/airport-transfers': typeof AirportTransfersRoute
  '/auth': typeof AuthRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/corporate-booking': typeof CorporateBookingRoute
  '/corporate-travel': typeof CorporateTravelRoute
  '/distance': typeof DistanceRoute
  '/drive-with-us': typeof DriveWithUsRoute
  '/fleet': typeof FleetRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tours': typeof ToursRoute
  '/vip-transfers': typeof VipTransfersRoute
  '/booking/$token': typeof BookingTokenRoute
  '/admin/addresses': typeof AuthenticatedAdminAddressesRoute
  '/admin/banned-addresses': typeof AuthenticatedAdminBannedAddressesRoute
  '/admin/bookings': typeof AuthenticatedAdminBookingsRoute
  '/admin/content': typeof AuthenticatedAdminContentRoute
  '/admin/coupons': typeof AuthenticatedAdminCouponsRoute
  '/admin/customers': typeof AuthenticatedAdminCustomersRoute
  '/admin/drivers': typeof AuthenticatedAdminDriversRoute
  '/admin/fleet': typeof AuthenticatedAdminFleetRoute
  '/admin/hourly-rate': typeof AuthenticatedAdminHourlyRateRoute
  '/admin/logs': typeof AuthenticatedAdminLogsRoute
  '/admin/messages': typeof AuthenticatedAdminMessagesRoute
  '/admin/mileage-pricing': typeof AuthenticatedAdminMileagePricingRoute
  '/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/pois': typeof AuthenticatedAdminPoisRoute
  '/admin/pricing': typeof AuthenticatedAdminPricingRoute
  '/admin/pricing-preview': typeof AuthenticatedAdminPricingPreviewRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/scenic-routes': typeof AuthenticatedAdminScenicRoutesRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/surcharges': typeof AuthenticatedAdminSurchargesRoute
  '/admin/tour-settings': typeof AuthenticatedAdminTourSettingsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/airport-transfers': typeof AirportTransfersRoute
  '/auth': typeof AuthRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/corporate-booking': typeof CorporateBookingRoute
  '/corporate-travel': typeof CorporateTravelRoute
  '/distance': typeof DistanceRoute
  '/drive-with-us': typeof DriveWithUsRoute
  '/fleet': typeof FleetRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tours': typeof ToursRoute
  '/vip-transfers': typeof VipTransfersRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/booking/$token': typeof BookingTokenRoute
  '/_authenticated/admin/addresses': typeof AuthenticatedAdminAddressesRoute
  '/_authenticated/admin/banned-addresses': typeof AuthenticatedAdminBannedAddressesRoute
  '/_authenticated/admin/bookings': typeof AuthenticatedAdminBookingsRoute
  '/_authenticated/admin/content': typeof AuthenticatedAdminContentRoute
  '/_authenticated/admin/coupons': typeof AuthenticatedAdminCouponsRoute
  '/_authenticated/admin/customers': typeof AuthenticatedAdminCustomersRoute
  '/_authenticated/admin/drivers': typeof AuthenticatedAdminDriversRoute
  '/_authenticated/admin/fleet': typeof AuthenticatedAdminFleetRoute
  '/_authenticated/admin/hourly-rate': typeof AuthenticatedAdminHourlyRateRoute
  '/_authenticated/admin/logs': typeof AuthenticatedAdminLogsRoute
  '/_authenticated/admin/messages': typeof AuthenticatedAdminMessagesRoute
  '/_authenticated/admin/mileage-pricing': typeof AuthenticatedAdminMileagePricingRoute
  '/_authenticated/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/_authenticated/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/_authenticated/admin/pois': typeof AuthenticatedAdminPoisRoute
  '/_authenticated/admin/pricing': typeof AuthenticatedAdminPricingRoute
  '/_authenticated/admin/pricing-preview': typeof AuthenticatedAdminPricingPreviewRoute
  '/_authenticated/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/_authenticated/admin/scenic-routes': typeof AuthenticatedAdminScenicRoutesRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/surcharges': typeof AuthenticatedAdminSurchargesRoute
  '/_authenticated/admin/tour-settings': typeof AuthenticatedAdminTourSettingsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/airport-transfers'
    | '/auth'
    | '/book'
    | '/contact'
    | '/corporate-booking'
    | '/corporate-travel'
    | '/distance'
    | '/drive-with-us'
    | '/fleet'
    | '/services'
    | '/sitemap.xml'
    | '/tours'
    | '/vip-transfers'
    | '/admin'
    | '/booking/$token'
    | '/admin/addresses'
    | '/admin/banned-addresses'
    | '/admin/bookings'
    | '/admin/content'
    | '/admin/coupons'
    | '/admin/customers'
    | '/admin/drivers'
    | '/admin/fleet'
    | '/admin/hourly-rate'
    | '/admin/logs'
    | '/admin/messages'
    | '/admin/mileage-pricing'
    | '/admin/notifications'
    | '/admin/payments'
    | '/admin/pois'
    | '/admin/pricing'
    | '/admin/pricing-preview'
    | '/admin/reports'
    | '/admin/scenic-routes'
    | '/admin/settings'
    | '/admin/surcharges'
    | '/admin/tour-settings'
    | '/admin/users'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/airport-transfers'
    | '/auth'
    | '/book'
    | '/contact'
    | '/corporate-booking'
    | '/corporate-travel'
    | '/distance'
    | '/drive-with-us'
    | '/fleet'
    | '/services'
    | '/sitemap.xml'
    | '/tours'
    | '/vip-transfers'
    | '/booking/$token'
    | '/admin/addresses'
    | '/admin/banned-addresses'
    | '/admin/bookings'
    | '/admin/content'
    | '/admin/coupons'
    | '/admin/customers'
    | '/admin/drivers'
    | '/admin/fleet'
    | '/admin/hourly-rate'
    | '/admin/logs'
    | '/admin/messages'
    | '/admin/mileage-pricing'
    | '/admin/notifications'
    | '/admin/payments'
    | '/admin/pois'
    | '/admin/pricing'
    | '/admin/pricing-preview'
    | '/admin/reports'
    | '/admin/scenic-routes'
    | '/admin/settings'
    | '/admin/surcharges'
    | '/admin/tour-settings'
    | '/admin/users'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/airport-transfers'
    | '/auth'
    | '/book'
    | '/contact'
    | '/corporate-booking'
    | '/corporate-travel'
    | '/distance'
    | '/drive-with-us'
    | '/fleet'
    | '/services'
    | '/sitemap.xml'
    | '/tours'
    | '/vip-transfers'
    | '/_authenticated/admin'
    | '/booking/$token'
    | '/_authenticated/admin/addresses'
    | '/_authenticated/admin/banned-addresses'
    | '/_authenticated/admin/bookings'
    | '/_authenticated/admin/content'
    | '/_authenticated/admin/coupons'
    | '/_authenticated/admin/customers'
    | '/_authenticated/admin/drivers'
    | '/_authenticated/admin/fleet'
    | '/_authenticated/admin/hourly-rate'
    | '/_authenticated/admin/logs'
    | '/_authenticated/admin/messages'
    | '/_authenticated/admin/mileage-pricing'
    | '/_authenticated/admin/notifications'
    | '/_authenticated/admin/payments'
    | '/_authenticated/admin/pois'
    | '/_authenticated/admin/pricing'
    | '/_authenticated/admin/pricing-preview'
    | '/_authenticated/admin/reports'
    | '/_authenticated/admin/scenic-routes'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/surcharges'
    | '/_authenticated/admin/tour-settings'
    | '/_authenticated/admin/users'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AirportTransfersRoute: typeof AirportTransfersRoute
  AuthRoute: typeof AuthRoute
  BookRoute: typeof BookRoute
  ContactRoute: typeof ContactRoute
  CorporateBookingRoute: typeof CorporateBookingRoute
  CorporateTravelRoute: typeof CorporateTravelRoute
  DistanceRoute: typeof DistanceRoute
  DriveWithUsRoute: typeof DriveWithUsRoute
  FleetRoute: typeof FleetRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ToursRoute: typeof ToursRoute
  VipTransfersRoute: typeof VipTransfersRoute
  BookingTokenRoute: typeof BookingTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vip-transfers': {
      id: '/vip-transfers'
      path: '/vip-transfers'
      fullPath: '/vip-transfers'
      preLoaderRoute: typeof VipTransfersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tours': {
      id: '/tours'
      path: '/tours'
      fullPath: '/tours'
      preLoaderRoute: typeof ToursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fleet': {
      id: '/fleet'
      path: '/fleet'
      fullPath: '/fleet'
      preLoaderRoute: typeof FleetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drive-with-us': {
      id: '/drive-with-us'
      path: '/drive-with-us'
      fullPath: '/drive-with-us'
      preLoaderRoute: typeof DriveWithUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/distance': {
      id: '/distance'
      path: '/distance'
      fullPath: '/distance'
      preLoaderRoute: typeof DistanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corporate-travel': {
      id: '/corporate-travel'
      path: '/corporate-travel'
      fullPath: '/corporate-travel'
      preLoaderRoute: typeof CorporateTravelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corporate-booking': {
      id: '/corporate-booking'
      path: '/corporate-booking'
      fullPath: '/corporate-booking'
      preLoaderRoute: typeof CorporateBookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/airport-transfers': {
      id: '/airport-transfers'
      path: '/airport-transfers'
      fullPath: '/airport-transfers'
      preLoaderRoute: typeof AirportTransfersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/$token': {
      id: '/booking/$token'
      path: '/booking/$token'
      fullPath: '/booking/$token'
      preLoaderRoute: typeof BookingTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/tour-settings': {
      id: '/_authenticated/admin/tour-settings'
      path: '/tour-settings'
      fullPath: '/admin/tour-settings'
      preLoaderRoute: typeof AuthenticatedAdminTourSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/surcharges': {
      id: '/_authenticated/admin/surcharges'
      path: '/surcharges'
      fullPath: '/admin/surcharges'
      preLoaderRoute: typeof AuthenticatedAdminSurchargesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/scenic-routes': {
      id: '/_authenticated/admin/scenic-routes'
      path: '/scenic-routes'
      fullPath: '/admin/scenic-routes'
      preLoaderRoute: typeof AuthenticatedAdminScenicRoutesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/reports': {
      id: '/_authenticated/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AuthenticatedAdminReportsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/pricing-preview': {
      id: '/_authenticated/admin/pricing-preview'
      path: '/pricing-preview'
      fullPath: '/admin/pricing-preview'
      preLoaderRoute: typeof AuthenticatedAdminPricingPreviewRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/pricing': {
      id: '/_authenticated/admin/pricing'
      path: '/pricing'
      fullPath: '/admin/pricing'
      preLoaderRoute: typeof AuthenticatedAdminPricingRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/pois': {
      id: '/_authenticated/admin/pois'
      path: '/pois'
      fullPath: '/admin/pois'
      preLoaderRoute: typeof AuthenticatedAdminPoisRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/payments': {
      id: '/_authenticated/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AuthenticatedAdminPaymentsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/notifications': {
      id: '/_authenticated/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AuthenticatedAdminNotificationsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/mileage-pricing': {
      id: '/_authenticated/admin/mileage-pricing'
      path: '/mileage-pricing'
      fullPath: '/admin/mileage-pricing'
      preLoaderRoute: typeof AuthenticatedAdminMileagePricingRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/messages': {
      id: '/_authenticated/admin/messages'
      path: '/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AuthenticatedAdminMessagesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/logs': {
      id: '/_authenticated/admin/logs'
      path: '/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AuthenticatedAdminLogsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/hourly-rate': {
      id: '/_authenticated/admin/hourly-rate'
      path: '/hourly-rate'
      fullPath: '/admin/hourly-rate'
      preLoaderRoute: typeof AuthenticatedAdminHourlyRateRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/fleet': {
      id: '/_authenticated/admin/fleet'
      path: '/fleet'
      fullPath: '/admin/fleet'
      preLoaderRoute: typeof AuthenticatedAdminFleetRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/drivers': {
      id: '/_authenticated/admin/drivers'
      path: '/drivers'
      fullPath: '/admin/drivers'
      preLoaderRoute: typeof AuthenticatedAdminDriversRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/customers': {
      id: '/_authenticated/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AuthenticatedAdminCustomersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/coupons': {
      id: '/_authenticated/admin/coupons'
      path: '/coupons'
      fullPath: '/admin/coupons'
      preLoaderRoute: typeof AuthenticatedAdminCouponsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/content': {
      id: '/_authenticated/admin/content'
      path: '/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AuthenticatedAdminContentRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/bookings': {
      id: '/_authenticated/admin/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AuthenticatedAdminBookingsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/banned-addresses': {
      id: '/_authenticated/admin/banned-addresses'
      path: '/banned-addresses'
      fullPath: '/admin/banned-addresses'
      preLoaderRoute: typeof AuthenticatedAdminBannedAddressesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/addresses': {
      id: '/_authenticated/admin/addresses'
      path: '/addresses'
      fullPath: '/admin/addresses'
      preLoaderRoute: typeof AuthenticatedAdminAddressesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminAddressesRoute: typeof AuthenticatedAdminAddressesRoute
  AuthenticatedAdminBannedAddressesRoute: typeof AuthenticatedAdminBannedAddressesRoute
  AuthenticatedAdminBookingsRoute: typeof AuthenticatedAdminBookingsRoute
  AuthenticatedAdminContentRoute: typeof AuthenticatedAdminContentRoute
  AuthenticatedAdminCouponsRoute: typeof AuthenticatedAdminCouponsRoute
  AuthenticatedAdminCustomersRoute: typeof AuthenticatedAdminCustomersRoute
  AuthenticatedAdminDriversRoute: typeof AuthenticatedAdminDriversRoute
  AuthenticatedAdminFleetRoute: typeof AuthenticatedAdminFleetRoute
  AuthenticatedAdminHourlyRateRoute: typeof AuthenticatedAdminHourlyRateRoute
  AuthenticatedAdminLogsRoute: typeof AuthenticatedAdminLogsRoute
  AuthenticatedAdminMessagesRoute: typeof AuthenticatedAdminMessagesRoute
  AuthenticatedAdminMileagePricingRoute: typeof AuthenticatedAdminMileagePricingRoute
  AuthenticatedAdminNotificationsRoute: typeof AuthenticatedAdminNotificationsRoute
  AuthenticatedAdminPaymentsRoute: typeof AuthenticatedAdminPaymentsRoute
  AuthenticatedAdminPoisRoute: typeof AuthenticatedAdminPoisRoute
  AuthenticatedAdminPricingRoute: typeof AuthenticatedAdminPricingRoute
  AuthenticatedAdminPricingPreviewRoute: typeof AuthenticatedAdminPricingPreviewRoute
  AuthenticatedAdminReportsRoute: typeof AuthenticatedAdminReportsRoute
  AuthenticatedAdminScenicRoutesRoute: typeof AuthenticatedAdminScenicRoutesRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminSurchargesRoute: typeof AuthenticatedAdminSurchargesRoute
  AuthenticatedAdminTourSettingsRoute: typeof AuthenticatedAdminTourSettingsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminAddressesRoute: AuthenticatedAdminAddressesRoute,
    AuthenticatedAdminBannedAddressesRoute:
      AuthenticatedAdminBannedAddressesRoute,
    AuthenticatedAdminBookingsRoute: AuthenticatedAdminBookingsRoute,
    AuthenticatedAdminContentRoute: AuthenticatedAdminContentRoute,
    AuthenticatedAdminCouponsRoute: AuthenticatedAdminCouponsRoute,
    AuthenticatedAdminCustomersRoute: AuthenticatedAdminCustomersRoute,
    AuthenticatedAdminDriversRoute: AuthenticatedAdminDriversRoute,
    AuthenticatedAdminFleetRoute: AuthenticatedAdminFleetRoute,
    AuthenticatedAdminHourlyRateRoute: AuthenticatedAdminHourlyRateRoute,
    AuthenticatedAdminLogsRoute: AuthenticatedAdminLogsRoute,
    AuthenticatedAdminMessagesRoute: AuthenticatedAdminMessagesRoute,
    AuthenticatedAdminMileagePricingRoute:
      AuthenticatedAdminMileagePricingRoute,
    AuthenticatedAdminNotificationsRoute: AuthenticatedAdminNotificationsRoute,
    AuthenticatedAdminPaymentsRoute: AuthenticatedAdminPaymentsRoute,
    AuthenticatedAdminPoisRoute: AuthenticatedAdminPoisRoute,
    AuthenticatedAdminPricingRoute: AuthenticatedAdminPricingRoute,
    AuthenticatedAdminPricingPreviewRoute:
      AuthenticatedAdminPricingPreviewRoute,
    AuthenticatedAdminReportsRoute: AuthenticatedAdminReportsRoute,
    AuthenticatedAdminScenicRoutesRoute: AuthenticatedAdminScenicRoutesRoute,
    AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
    AuthenticatedAdminSurchargesRoute: AuthenticatedAdminSurchargesRoute,
    AuthenticatedAdminTourSettingsRoute: AuthenticatedAdminTourSettingsRoute,
    AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AirportTransfersRoute: AirportTransfersRoute,
  AuthRoute: AuthRoute,
  BookRoute: BookRoute,
  ContactRoute: ContactRoute,
  CorporateBookingRoute: CorporateBookingRoute,
  CorporateTravelRoute: CorporateTravelRoute,
  DistanceRoute: DistanceRoute,
  DriveWithUsRoute: DriveWithUsRoute,
  FleetRoute: FleetRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ToursRoute: ToursRoute,
  VipTransfersRoute: VipTransfersRoute,
  BookingTokenRoute: BookingTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
